### ISSUE TITLE
Support for .net core 3.1/standard?

### ISSUE THREAD

**Issue by rpgmaker** [Telerivet/telerivet-dotnet-client#2]
Is it possible to add support for the recent .net 5/.net core 3.1/.net standard 2.0-2.1?

**Comment by huaxing-yuan** [comment]
+1
Hi, our organization uses Telerivet service via this package. All pre 4.7 .net framework are obsolete in our organization and many projects have been migrated to .net 6.0. 
Is it possible to update this library in order to support .net core ? 

Thanks.

**Comment by youngj** [comment]
We just published a new version that supports .net 6.0 (https://www.nuget.org/packages/Telerivet.NET/1.7.1). To target other versions of .net it is currently necessary to build the library from source.
